# Generated by Django 5.0 on 2024-01-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='bio',
            field=models.TextField(default='Hello world'),
        ),
    ]
