# Generated by Django 5.0 on 2024-02-01 16:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_resume_education_remove_resume_experience_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="heading",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="intro_paragraph",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="subheading",
        ),
    ]
