# Generated by Django 5.0 on 2024-02-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_resume_heading_remove_resume_intro_paragraph_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
